# Generated by Django 3.1.6 on 2021-02-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210203_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default=0, upload_to='posts'),
            preserve_default=False,
        ),
    ]
