# Generated by Django 3.1.6 on 2021-02-03 19:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210203_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
