# Generated by Django 3.1.6 on 2021-02-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nrTelCelular',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular'),
        ),
    ]
