# Generated by Django 3.1.6 on 2021-02-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_contact_nrtelcelular'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apresent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
