# Generated by Django 3.1.6 on 2021-02-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20210209_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
